interface SpartanEvent {
  id: number;
  event: string;
  startDate: string;
  startAt: string;
  endDate: string;
  endAt: string;
  location: string;
  category: string;
  description: string;
  facility: string;
}

export const SPARTAN_EVENTS_MOCK: SpartanEvent[] = [
  {
    id:1,
    event: "Men's Track and Field vs U Sports Championships",
    startDate: '3/8/2024',
    startAt: '1:00PM',
    endDate: '3/8/2024',
    endAt: '4:00 PM',
    location: 'Winnipeg, MB',
    category: "Men's Track and Field",
    description: "Men's Track and Field vs U Sports Championships Winnipeg, MB",
    facility: 'James Daly Fieldhouse',
  },
  {
    id: 2,
    event: "Women's Track and Field vs U SPORTS Championships",
    startDate: '3/8/2024',
    startAt: '1:00PM',
    endDate: '3/8/2024',
    endAt: '4:00 PM',
    location: 'Winnipeg, MB',
    category: "Women's Track and Field",
    description: "Women's Track and Field vs U SPORTS Championships Winnipeg, MB",
    facility: 'James Daly Fieldhouse',
  },
  {
    id: 3,
    event: "Men's Volleyball at Alberta",
    startDate: '3/8/2024',
    startAt: '8:00PM',
    endDate: '3/8/2024',
    endAt: '11:00 PM',
    location: 'Edmonton, AB',
    category: "Men's Volleyball",
    description: "Men's Volleyball at Alberta Edmonton, AB",
    facility: 'Van Vliet Complex | Main Gym',
  },
  {
    id: 4,
    event: "Women's Soccer vs Vancouver Whitecaps FC (REX)",
    startDate: '3/8/2024',
    startAt: '8:00PM',
    endDate: '3/8/2024',
    endAt: '11:00 PM',
    location: 'Langley, BC',
    category: "Women's Soccer",
    description: "Women's Soccer vs Vancouver Whitecaps FC (REX) Langley, BC",
    facility: '',
  },
  {
    id: 5,
    event: "Men's Track and Field vs U Sports Championships",
    startDate: '3/9/2024',
    startAt: '12:30PM',
    endDate: '3/9/2024',
    endAt: '3:30 PM',
    location: 'Winnipeg, MB',
    category: "Men's Track and Field",
    description: "Men's Track and Field vs U Sports Championships Winnipeg, MB",
    facility: 'James Daly Fieldhouse',
  },
  {
    id: 6,
    event: "Men's Volleyball at Queen's",
    startDate: '3/14/2024',
    startAt: '5:00PM',
    endDate: '3/14/2024',
    endAt: '8:00 PM',
    location: 'Kingston, Ont.',
    category: "Men's Volleyball",
    description: "Men's Volleyball at Queen's Kingston, Ont.",
    facility: "Queen's Athletics and Recreation Centre",
  },
  {
    id: 7,
    event: "Men's Disc Golf  Northwest Collegiate Invitational",
    startDate: '3/16/2024',
    startAt: '',
    endDate: '3/16/2024',
    endAt: '11:59 PM',
    location: ' Estacada, OR',
    category: "Men's Disc Golf",
    description: "Men's Disc Golf  Northwest Collegiate Invitational  Estacada, OR",
    facility: 'Milo McIver Disc Golf Course',
  },
  {
    id: 8,
    event: "Women's Soccer vs UBC",
    startDate: '3/16/2024',
    startAt: '12:00PM',
    endDate: '3/16/2024',
    endAt: '3:00 PM',
    location: 'Victoria, BC',
    category: "Women's Soccer",
    description: "Women's Soccer vs UBC Victoria, BC",
    facility: 'Centennial Stadium',
  },
  {
    id: 9,
    event: "Men's Soccer vs UBC",
    startDate: '3/16/2024',
    startAt: '2:15PM',
    endDate: '3/16/2024',
    endAt: '5:15 PM',
    location: 'Victoria, BC',
    category: "Men's Soccer",
    description: "Men's Soccer vs UBC Victoria, BC",
    facility: 'Centennial Stadium',
  },
  {
    id: 10,
    event: "Men's Rugby at Pacific Pride",
    startDate: '3/16/2024',
    startAt: '4:30PM',
    endDate: '3/16/2024',
    endAt: '7:30 PM',
    location: 'Duncan, BC',
    category: "Men's Rugby",
    description: "Men's Rugby at Pacific Pride Duncan, BC",
    facility: 'Cowichan Rugby Club',
  },
  {
    id: 11,
    event: "Men's Volleyball vs Guelph",
    startDate: '3/16/2024',
    startAt: '5:00PM',
    endDate: '3/16/2024',
    endAt: '8:00 PM',
    location: 'Kingston, Ont.',
    category: "Men's Volleyball",
    description: "Men's Volleyball vs Guelph Kingston, Ont.",
    facility: "Queen's Athletics and Recreation Centre",
  },
  {
    id: 12,
    event: "Men's Disc Golf  Northwest Collegiate Invitational",
    startDate: '3/17/2024',
    startAt: '10:00AM',
    endDate: '3/17/2024',
    endAt: '1:00 PM',
    location: 'Estacada, Oregon ',
    category: "Men's Disc Golf",
    description: "Men's Disc Golf  Northwest Collegiate Invitational Estacada, Oregon ",
    facility: 'Milo McIver Disc Golf Course',
  },
  {
    id: 13,
    event: "Men's Volleyball vs Laval",
    startDate: '3/17/2024',
    startAt: '12:00PM',
    endDate: '3/17/2024',
    endAt: '3:00 PM',
    location: 'Kingston, Ont.',
    category: "Men's Volleyball",
    description: "Men's Volleyball vs Laval Kingston, Ont.",
    facility: "Queen's Athletics and Recreation Centre",
  },
  {
    id: 14,
    event: "Women's Soccer vs Fraser Valley",
    startDate: '3/17/2024',
    startAt: '12:00PM',
    endDate: '3/17/2024',
    endAt: '3:00 PM',
    location: 'Victoria, BC',
    category: "Women's Soccer",
    description: "Women's Soccer vs Fraser Valley Victoria, BC",
    facility: 'Centennial Stadium',
  },
  {
    id: 15,
    event: "Men's Soccer vs Fraser Valley ",
    startDate: '3/17/2024',
    startAt: '6:00PM',
    endDate: '3/17/2024',
    endAt: '9:00 PM',
    location: 'Victoria, BC',
    category: "Men's Soccer",
    description: "Men's Soccer vs Fraser Valley  Victoria, BC",
    facility: 'Centennial Stadium',
  },
//   {
//     event: "Men's Rugby vs 2nd XVs vs. Western Washington",
//     startDate: '3/23/2024',
//     startAt: '4:30PM',
//     endDate: '3/23/2024',
//     endAt: '7:30 PM',
//     location: 'Langley, BC',
//     category: "Men's Rugby",
//     description: "Men's Rugby vs 2nd XVs vs. Western Washington Langley, BC",
//     facility: 'Willoughby Community Park Stadium',
//   },
//   {
//     event: "Women's Soccer vs Simon Fraser",
//     startDate: '3/27/2024',
//     startAt: '9:30PM',
//     endDate: '3/28/2024',
//     endAt: '12:30 AM',
//     location: 'Langley, BC',
//     category: "Women's Soccer",
//     description: "Women's Soccer vs Simon Fraser Langley, BC",
//     facility: 'Chase Office Field',
//   },
//   {
//     event: "Women's Rugby vs Army",
//     startDate: '3/29/2024',
//     startAt: '2:00PM',
//     endDate: '3/29/2024',
//     endAt: '5:00 PM',
//     location: 'Tampa, FL',
//     category: "Women's Rugby",
//     description: "Women's Rugby vs Army Tampa, FL",
//     facility: 'Tampa Sportsplex',
//   },
//   {
//     event: "Women's Rugby vs Clemson",
//     startDate: '3/29/2024',
//     startAt: '4:20PM',
//     endDate: '3/29/2024',
//     endAt: '7:20 PM',
//     location: 'Tampa, FL',
//     category: "Women's Rugby",
//     description: "Women's Rugby vs Clemson Tampa, FL",
//     facility: 'Tampa Sportsplex',
//   },
//   {
//     event: "Women's Rugby vs Dartmouth",
//     startDate: '3/29/2024',
//     startAt: '6:20PM',
//     endDate: '3/29/2024',
//     endAt: '9:20 PM',
//     location: 'Tampa, FL',
//     category: "Women's Rugby",
//     description: "Women's Rugby vs Dartmouth Tampa, FL",
//     facility: 'Tampa Sportsplex',
//   },
//   {
//     event: "Women's Rugby vs Quinnipiac",
//     startDate: '3/30/2024',
//     startAt: '3:00PM',
//     endDate: '3/30/2024',
//     endAt: '6:00 PM',
//     location: 'Tampa, FL',
//     category: "Women's Rugby",
//     description: "Women's Rugby vs Quinnipiac Tampa, FL",
//     facility: 'Tampa Sportsplex',
//   },
//   {
//     event: "Men's Rugby at Central Washington",
//     startDate: '3/30/2024',
//     startAt: '4:00PM',
//     endDate: '3/30/2024',
//     endAt: '7:00 PM',
//     location: 'Ellensburg, WA',
//     category: "Men's Rugby",
//     description: "Men's Rugby at Central Washington Ellensburg, WA",
//     facility: 'Tomlinson Stadium',
//   },
//   {
//     event: "Women's Rugby vs Brown",
//     startDate: '3/30/2024',
//     startAt: '4:40PM',
//     endDate: '3/30/2024',
//     endAt: '7:40 PM',
//     location: 'Tampa, FL',
//     category: "Women's Rugby",
//     description: "Women's Rugby vs Brown Tampa, FL",
//     facility: 'Tampa Sportsplex',
//   },
//   {
//     event: "Women's Rugby vs Harvard",
//     startDate: '3/30/2024',
//     startAt: '6:40PM',
//     endDate: '3/30/2024',
//     endAt: '9:40 PM',
//     location: 'Tampa, FL',
//     category: "Women's Rugby",
//     description: "Women's Rugby vs Harvard Tampa, FL",
//     facility: 'Tampa Sportsplex',
//   },
//   {
//     event: "Men's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/3/2024',
//     startAt: '',
//     endDate: '4/5/2024',
//     endAt: '11:59 PM',
//     location: 'Rock Hill, SC',
//     category: "Men's Disc Golf",
//     description: "Men's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Women's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/3/2024',
//     startAt: '',
//     endDate: '4/5/2024',
//     endAt: '11:59 PM',
//     location: 'Rock Hill, SC',
//     category: "Women's Disc Golf",
//     description: "Women's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Men's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/4/2024',
//     startAt: '7:00AM',
//     endDate: '4/4/2024',
//     endAt: '10:00 AM',
//     location: 'Rock Hill, SC',
//     category: "Men's Disc Golf",
//     description: "Men's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Women's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/4/2024',
//     startAt: '8:00AM',
//     endDate: '4/4/2024',
//     endAt: '11:00 AM',
//     location: 'Rock Hill, SC',
//     category: "Women's Disc Golf",
//     description: "Women's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Men's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/5/2024',
//     startAt: '7:30AM',
//     endDate: '4/5/2024',
//     endAt: '10:30 AM',
//     location: 'Rock Hill, SC',
//     category: "Men's Disc Golf",
//     description: "Men's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Women's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/5/2024',
//     startAt: '8:10AM',
//     endDate: '4/5/2024',
//     endAt: '11:10 AM',
//     location: 'Rock Hill, SC',
//     category: "Women's Disc Golf",
//     description: "Women's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Men's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/6/2024',
//     startAt: '7:49AM',
//     endDate: '4/6/2024',
//     endAt: '10:49 AM',
//     location: 'Rock Hill, SC',
//     category: "Men's Disc Golf",
//     description: "Men's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Women's Disc Golf  Collegiate Disc Golf National Championship",
//     startDate: '4/6/2024',
//     startAt: '8:10AM',
//     endDate: '4/6/2024',
//     endAt: '11:10 AM',
//     location: 'Rock Hill, SC',
//     category: "Women's Disc Golf",
//     description: "Women's Disc Golf  Collegiate Disc Golf National Championship Rock Hill, SC",
//     facility: '',
//   },
//   {
//     event: "Women's Soccer vs Seattle",
//     startDate: '4/6/2024',
//     startAt: '5:00PM',
//     endDate: '4/6/2024',
//     endAt: '8:00 PM',
//     location: 'Langley, BC',
//     category: "Women's Soccer",
//     description: "Women's Soccer vs Seattle Langley, BC",
//     facility: 'Chase Office Field',
//   },
//   {
//     event: "Women's Soccer at Western Washington",
//     startDate: '4/9/2024',
//     startAt: '9:00PM',
//     endDate: '4/9/2024',
//     endAt: '11:59 PM',
//     location: 'Bellingham, WA',
//     category: "Women's Soccer",
//     description: "Women's Soccer at Western Washington Bellingham, WA",
//     facility: 'Harrington Field',
//   },
//   {
//     event: "Women's Soccer vs Gonzaga",
//     startDate: '4/13/2024',
//     startAt: '6:00PM',
//     endDate: '4/13/2024',
//     endAt: '9:00 PM',
//     location: 'Langley, BC',
//     category: "Women's Soccer",
//     description: "Women's Soccer vs Gonzaga Langley, BC",
//     facility: 'Chase Office Field',
//   },
];
